call plug#begin()

Plug 'tpope/vim-commentary' " easy way to comment the code

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim' " ack in vim
Plug 'davidhalter/jedi-vim' " autocomplete syntax
Plug 'w0rp/ale' " lint engine
Plug 'morhetz/gruvbox' " theme
Plug 'scrooloose/nerdtree' " simple tree file manager
Plug 'pangloss/vim-javascript' " js syntax highlighting
Plug 'elixir-editors/vim-elixir' " elixir

call plug#end()

" set background=dark
set encoding=utf-8
set relativenumber
set number " set hybrid mode
set title 
set hidden " https://stackoverflow.com/questions/17705331/exit-temporary-modified-file-without-saving-and-jump-back-to-my-previous-viewing
set exrc " enable per-directory .vimrc files
set nobackup
set background=dark
set t_Co=256
set expandtab " converts tab to space

if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    set t_ut=
endif

colorscheme gruvbox
syntax on

" fzf
map <C-p> :GFiles<CR>

" ack remap
cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>

autocmd FileType coffee setlocal shiftwidth=4 tabstop=4
autocmd FileType cs setlocal shiftwidth=4 tabstop=4
autocmd FileType cpp setlocal noexpandtab
autocmd FileType html setlocal shiftwidth=4 tabstop=4
autocmd FileType htmldjango setlocal shiftwidth=4 tabstop=4
autocmd FileType java setlocal noexpandtab
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType typescript setlocal shiftwidth=2 tabstop=2
autocmd FileType scss setlocal shiftwidth=2 tabstop=2
autocmd FileType css setlocal shiftwidth=2 tabstop=2
autocmd FileType xhtml setlocal shiftwidth=4 tabstop=4
autocmd FileType xml setlocal shiftwidth=4 tabstop=4
autocmd FileType yaml setlocal shiftwidth=2 tabstop=2

let NERDTreeIgnore = ['\.pyc$', '\.pdf$', '__pycache__']
let g:javascript_plugin_jsdoc = 1 " Enables syntax highlighting for JSDocs.

" ale 
let g:ale_fixers = {
    \ 'css': ['prettier'],
    \ 'javascript': ['prettier'],
    \ 'python': ['black'],
    \ }
let g:ale_linters = {
    \ 'python': ['flake8'],
    \ }
let g:ale_fix_on_save = 1
let g:ale_virtualenv_dir_names = ['.env', '.venv', 'env', 'venv']
let g:ale_python_black_options = '--line-length=100 --safe'
let g:ale_python_flake8_options = '--ignore=E501'

" Disable Arrow keys in Escape mode
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Disable Arrow keys in Insert mode
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

