call plug#begin()

Plug 'tpope/vim-commentary' " easy way to comment the code

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim' " ack in vim
Plug 'davidhalter/jedi-vim' " autocomplete syntax

call plug#end()

" set background=dark
set encoding=utf-8
set relativenumber
set title 

" fzf
map <C-p> :Files<CR>

" ack remap
cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>

" Disable Arrow keys in Escape mode
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Disable Arrow keys in Insert mode
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

